### ISSUE TITLE
Whitelist storage.googleapis.com

### ISSUE THREAD

**Issue by natanlao** [davidonzo/Threat-Intel#10]
Hi! Please whitelist storage.googleapis.com. It's used for Google Cloud Storage. Thanks.

**Comment by davidonzo** [comment]
Hi natanlao,

Did it. Thanks for you advise.
Please, check yourself the lists and close the issue if you consider it solved.

Best regards
--
DB

**Comment by natanlao** [comment]
Confirmed that it's no longer being blocked, thanks so much.
