### ISSUE TITLE
Possible commits/scripts malfunctions

### ISSUE THREAD

**Issue by dnmTX** [davidonzo/Threat-Intel#14]
Hi Davide @davidonzo. Your list was part of [Steven Black's hosts](https://github.com/StevenBlack/hosts) but it was recently removed by the repo owner @StevenBlack when he noticed some [commits inconcistencies](https://github.com/StevenBlack/hosts/commit/9b412a7cbfd726faed9019c27f660b15972598b1). 👈 follow up on the conversation there ❗ 
Could you please inspect/fix or maybe shed some light on the process if there are no problems so we can get your list back.
Thank you and keep up the good work. 👍

**Comment by davidonzo** [comment]
As replied in the linked thread:

Every domain listed in the list is related to a malware downloaded by my personal malware analysis lab.
The list is extracted by a MISP instance using the "last":"7d" filter.

What you noticed is right, and it depends on some problem I had with the related MISP instance.

I purged lots of out of dated data from MISP and fixed the problem.
Now the situation is stable.

I'll continue to share the file in piHole format, so you are able to add the source again on your choise.

Thanks for your attention and sorry for this matter.

**Comment by dnmTX** [comment]
Thanks again,closing this as my mission was accomplished here 😄
