### ISSUE TITLE
files.catbox.moe

### ISSUE THREAD

**Issue by NO-ob** [davidonzo/Threat-Intel#15]
Would it be possible to get files.catbox.moe removed from the list? I'm not sure why it would be on the list in the first place

**Comment by davidonzo** [comment]
3 malicious url detected in the latest week.
Anyway, I can remove the domain withelisting it, considering the main pourpose.

Next run the domain will be removed from the domain list, but related malicious urls will be shared in the urls list.

**Comment by davidonzo** [comment]
Domain removed as expected.

**Comment by NO-ob** [comment]
Awesome thankyou
