### ISSUE TITLE
Backblaze

### ISSUE THREAD

**Issue by StevenBlack** [davidonzo/Threat-Intel#17]
Hi Davide @davidonzo please see https://github.com/StevenBlack/hosts/issues/1526 — Backblaze is being blocked and I cannot imagine why.  Can you investigate?  Thanks!

**Comment by davidonzo** [comment]
Hi Steven,

A malicious file has been shared via Backblaze.
This is the link to the latest VT report: https://www.virustotal.com/gui/file/bad08112a53a47a5bb856c7caad96f00ff2d29d109aee9118b56a5a62e59f5ef/detection

Anyway, as ever in these cases, I added the related host to the whitelist.
Considering the event, I'm running a new job to generate the repository content. It will finish in minutes.

Thanks for the advice.

Ciao!
--
DB
