### ISSUE TITLE
whitelist deac-ams.dl.sourceforge.net

### ISSUE THREAD

**Issue by scafroglia93** [davidonzo/Threat-Intel#18]
https://github.com/davidonzo/Threat-Intel/blob/6aaceb91d900740fe449497c3b76fbda237fc298/lists/latestdomains.txt#L22

used by sourceforge.net

thanks

**Comment by davidonzo** [comment]
Thanks.
Domain added to whitelist.

Lists will be updated soon.

Please, close the issue when you consider it to be closed.
Regards
--
Davide

**Comment by scafroglia93** [comment]
many thanks
