### ISSUE TITLE
transfer.sh blocked

### ISSUE THREAD

**Issue by hectorm** [davidonzo/Threat-Intel#19]
Hi @davidonzo, please check hectorm/hmirror#10, transfer.sh is being blocked.

**Comment by davidonzo** [comment]
12 malicious files delivered by the domain from 09th of September. One per day.
Not a good domain IHMO

**Comment by hyder365** [comment]
This is a legitimate site for file sharing, especially in tech circles due to its easy curl integration. It's not malicious in and of itself at all.

**Comment by davidonzo** [comment]
Domain whitelisted.
Malicious URLs will remain in the "latesturls.txt" file as usual.

Feel free to close the issue if and when you think it is solved.
