### ISSUE TITLE
Typo at https://osint.digitalside.it/

### ISSUE THREAD

**Issue by icepaule** [davidonzo/Threat-Intel#2]
Hi Davide and thank you very much making the MISP-feed available for the community.
As I'm writing about it at my blog (https://www.mpauli.de/cybernews.php), I found a typo you might want to correct.

"This repository co**i**ntains a set ..." should be "This repository **contains** a set" ;-)

Again, thx for all the cool work.

Cheers
Marcus

**Comment by davidonzo** [comment]
Thank you for the hunted typo. Corrected both on website and the README.md file with commit [33b7241](https://github.com/davidonzo/Threat-Intel/commit/33b72419fa46b72d63e7ad8888e9f4aa676819ef)

And thank you  very much for your article! Very appreciated!
