### ISSUE TITLE
Bitbucket blocked

### ISSUE THREAD

**Issue by timdonovanuk** [davidonzo/Threat-Intel#20]
Bitbucket is a Git-based source code repository hosting service owned by Atlassian. It's huge. It should not be blocked at the root level.

**Comment by cdanderson** [comment]
Another vote on this issue here. Thank you, @timdonovanuk.

**Comment by davidonzo** [comment]
Domain whitelisted.
Malicious URLs will remain in the "latesturls.txt" file as usual.
