### ISSUE TITLE
[false-positive]  www.zipshare.com

### ISSUE THREAD

**Issue by dnmTX** [davidonzo/Threat-Intel#21]
Hi there @davidonzo 👋 
Your latest commit included the mentioned domain and it's a false-positive fo sure,likely somebody tried to distribute some nastiness from there but nevertheless has to be whitelisted before the issues start piling up in [Steven's repo](https://github.com/StevenBlack/hosts).
Thank you as allways 👍

**Comment by davidonzo** [comment]
Sorry for the delayed response.
Solved.

Lists updated.
