### ISSUE TITLE
[False Positive] Dropbox : dl.dropboxusercontent.com

### ISSUE THREAD

**Issue by Belphemur** [davidonzo/Threat-Intel#22]
Hello,

The domain used by dropbox to provide file download has been blocked:
`dl.dropboxusercontent.com` 

I've reported it to the Steven Black blocklist that had your blocklist as feed:
https://github.com/StevenBlack/hosts/issues/1868

You might want to rework your url sanitization to domain, because for some service like Imgur, Dropbox, etc ... blocking the domain isn't a good idea when working from the URL.

**Comment by davidonzo** [comment]
Domain added to the whitelist.
URLs are malicious, so them will be maintained in the latesturls.txt file.

New lists will be published in minutes.

Thanks for your advice
