### ISSUE TITLE
Oh , god ............ harder to use more good tools

### ISSUE THREAD

**Issue by hujiujiu** [davidonzo/Threat-Intel#26]
![图片](https://user-images.githubusercontent.com/62174656/193450462-c3a63419-a566-4d19-b8ff-80db876abd23.png)

**Comment by hujiujiu** [comment]
realy sad for both can't be downloaded ...............................

**Comment by davidonzo** [comment]
Sorry for the delay in answer.

Should be fixed now.
Please, let me know if it's ok for you.

Regards
