### ISSUE TITLE
VK.com

### ISSUE THREAD

**Issue by jult** [davidonzo/Threat-Intel#27]
Why on earth are you blocking/blacklisting VK ?
This site is actually more secure and safe than facebook, for crying out loud.

I urge everyone reading this to stop using your lists, blocking VKontakte are you freaking kidding us?

**Comment by fireglow** [comment]
I don't understand the reason behind this. The list has become useless for me.

**Comment by jult** [comment]
I guess it is a by-product of the inane (yes, without the s) russophobic BS that is taking over the hypocritical 'collective West'. [I've written](https://jult.net/2022/03/03/putin-is-not-evil) [a couple of pieces](https://jult.net/2022/06/07/what-were-russia-and-the-west-arguing-about) [about it](https://jult.net/2022/11/04/nukes). I recommend @davidonzo to read some more and then judge again.

**Comment by davidonzo** [comment]
It was just my mistake. Processes for adding new IoC are 90% automated and false positive are not excluded at all.
Nothing related to russophobia or something similar...

It's important to understand lists produced by the service are unable to block anything...

Site added to the whitelist.

Sorry for the delay in the answer (some personal problem occurred) and many thanks for reporting the issue.

I'll close the issue in a couple of day in case anyone want to reply.
Regards
