### ISSUE TITLE
Codeberg.org should be whitelisted

### ISSUE THREAD

**Issue by TechScribe-Deaf** [davidonzo/Threat-Intel#29]
Hello, there were some users mentioning that they are seeing Codeberg.org blocked when using your blocklist. Codeberg is a non-profit organization dedicated toward hosting FOSS projects similar to Gitlab and Github. There's really no reason as far as I'm aware of to block Codeberg.org.

Please and thank you.

**Comment by davidonzo** [comment]
Sorry for the delay in the answer. 

The domain has been places in whitelist a week ago. So, new malicious urls will be reported in the malware urls list, but the domain will be excluded to be listed in the domains list.

Hope this help

Regards
