### ISSUE TITLE
Error adding Wasabisys CDN mirror

### ISSUE THREAD

**Issue by jsanchez0x** [davidonzo/Threat-Intel#30]
`s3.eu-central-2.wasabisys.com`

This should be deleted. It is a mistake to treat it as a problem because it is a CDN with no intention of serving malware or any malicious content.

It is currently interfering with the loading of images from the Mastodon instance mastodon.world.

I refer to the Pihole list where it has given me problems but it should be removed from the rest of the lists.

Thank you.

https://github.com/davidonzo/Threat-Intel/blame/29e3f46371b5de195f00b0b9bf3ca5f349ee66a4/lists/latestdomains.piHole.txt#L69

**Comment by davidonzo** [comment]
Added to white list.
Thanks
