### ISSUE TITLE
[Unblock Request] Trello (trello.com)

### ISSUE THREAD

**Issue by LXGaming** [davidonzo/Threat-Intel#31]
Trello is a web-based, kanban-style, list-making application and is developed by Trello Enterprise, a subsidiary of Atlassian.

It appears that the domain `trello.com` has been blocked possibly due to a malicious attachment being found, I do not believe the entire domain should be blocked.

**Comment by MariusGGS** [comment]
Many people use Trello for work related reasons, blocking it doesn't make sense. It's not a malicious website.

**Comment by ThatCoffeeGuy** [comment]
I was just about to open this issue. It is still blocked.

**Comment by StephenDaDev** [comment]
Also came to open this issue, can also confirm, not malicious and a legit service.

**Comment by KnightArch** [comment]
I also came here to open an issue about trello. Please, remove this block from the list. Maybe the intention was to block `sptrack.trello.com` sub-domain and not the domain `trello.com`.

**Comment by ilpianista** [comment]
> It appears that the domain `trello.com` has been blocked possibly due to a malicious attachment being found, I do not believe the entire domain should be blocked.

https://osint.digitalside.it/report/a0d1746d8f767d71f4db65ebeef93a41.html

I've reported the user to Atlassian.

**Comment by ilpianista** [comment]
> @ilpianista What did it show? I'm assuming I can safely whitelist trello.com on my PiHole, but I'm still curious to know what caused this to be blocked in the first place.

It's because of [this](https://trello.com/u/mariedwu9doria/activity) user uploading malware. Atlassian completely ignored my report.

**Comment by davidonzo** [comment]
Added to white list
Sorry for the delay in the answer
