### ISSUE TITLE
Should the IP list be blocked for ingress on the firewall

### ISSUE THREAD

**Issue by user8446** [davidonzo/Threat-Intel#34]
Hi,

I want to add the [IP list](https://osint.digitalside.it/Threat-Intel/lists/latestips.txt) to my firewall. Reading through your site it mentions "compromised URLs, IPs and domains" so we should obviously block egress traffic to these IP's. 

Are these also IP's that have been associated with attacks where they should be block for ingress traffic as well?

Thank you

**Comment by davidonzo** [comment]
Ciao Glenn,

All IoCs collected and shared are about malwares hosting and download. So, egress traffic is the target.
Anyway I cannot exclude at all the same infrastructure is used as C2 server or any other type of over and cover channels.

Don't have a definitive answer. It depends on scenario.
