### ISSUE TITLE
[Unblock Request]

### ISSUE THREAD

**Issue by sm4ckenzie** [davidonzo/Threat-Intel#35]
repository.eset.com is a false positive. Eset is an AV company.

**Comment by davidonzo** [comment]
Domain added to OSINT-DS white list => [c8282d951009fd21dc8d8bd036a3ac3d082dba6e](https://github.com/davidonzo/Threat-Intel-Domain-WL/commit/c8282d951009fd21dc8d8bd036a3ac3d082dba6e)

Thanks for the advice.
Regards
