### ISSUE TITLE
[False positive] web.archive.org

### ISSUE THREAD

**Issue by espressoelf** [davidonzo/Threat-Intel#46]
https://github.com/davidonzo/Threat-Intel/blob/82ff2b29fc2951324b0623d6b6689402bb1bed51/lists/latestdomains.txt#L88
https://github.com/davidonzo/Threat-Intel/blob/82ff2b29fc2951324b0623d6b6689402bb1bed51/lists/latestdomains.piHole.txt#L88

Belongs to the Internet Archive, one of the good guys. :)

**Comment by tayl** [comment]
+1, just ran into this and came to make this issue.
