### ISSUE TITLE
[False positive] autohotkey.com

### ISSUE THREAD

**Issue by gvieiraaa** [davidonzo/Threat-Intel#48]
autohotkey.com is a false positive

It's a reputable, open source programming language

https://github.com/davidonzo/Threat-Intel/blob/ff1fe77e4c027e36728757f7aec3a4275141c57c/lists/latestdomains.txt#L111

**Comment by davidonzo** [comment]
It seems a malicious file is spreads via the domain and the file is still downloadable.
Is this a file positive? => https://www.virustotal.com/gui/file/a824f1fcb19bb9562af33173b1f5cee6f26541614912821d38733fa5f0afeaf1?nocache=1

**Comment by gvieiraaa** [comment]
> It seems a malicious file is spreads via the domain and the file is still downloadable. Is this a file positive? => https://www.virustotal.com/gui/file/a824f1fcb19bb9562af33173b1f5cee6f26541614912821d38733fa5f0afeaf1?nocache=1

It's a false positive. Since autohotkey is a language very focused on wrapping the windows API, there are malwares that use it bundled with their malicious code to execute it. That makes a few security vendors to flag it as malicious too.

Your VT link is for v1.1.23.04, released in march 2016, but even the [latest release of v1](https://www.virustotal.com/gui/file/ba35b8b4346b79b8bb4f97360025cb6befaf501b03149a3b5fef8f07bdf265c7?nocache=1), from march 2024, has false positives.

**Comment by davidonzo** [comment]
Ok, added to the whitelist => https://github.com/davidonzo/Threat-Intel-Domain-WL/commit/33a3c765d687ae6449aa5cce195f28204d4c06a3

The feed will be updated in minutes.
Thanks for the opened issue!

Regards
