### ISSUE TITLE
FP: cdn.discordapp.com

### ISSUE THREAD

**Issue by ibell63** [davidonzo/Threat-Intel#5]
https://github.com/davidonzo/Threat-Intel/blob/10b4beb3163ce1cc02f3f2b796664be06e582c05/lists/latestdomains.txt#L34

You have an FP in this list: cdn.discordapp.com

**Comment by davidonzo** [comment]
Actually there's no active detected threat on the host, so I decided to remove the domain attribute from the lists.

But I can't consider it a false positive according this report: https://github.com/davidonzo/host/blob/master/ExportReport2020_02_23_11_48_15_OSINTDS_Backend.csv

Can yuo give me any reason to consider it a FP and whitelist it?

**Comment by ibell63** [comment]
Discord is a popular VoIP chat service, like Teamspeak or Ventrillo.  It also has chat features like Slack or Microsoft Teams.  Presumably, the detections you are seeing are from a file transfer service that’s built-in.  The name implies to me that this entry is for their CDN, meaning that blacklisting this entry would block all file transfers on the service and probably other important functions.

**Comment by davidonzo** [comment]
CDN hosts often create this kind of security related issues.
You are right about the related problems can create to a network blocking this kinds of hosts, but sometimes Is a good solution.

Considering the domain history discordapp staff and the cdn service provider should work much to protect them customers and not only.

Remember, the pourpose of the shared lists is just the sharing itself. Using them as a blocklist is a personal choise.
