### ISSUE TITLE
[False Positive] discord.com

### ISSUE THREAD

**Issue by LXGaming** [davidonzo/Threat-Intel#50]
Discord is an instant messaging and VoIP social platform which allows communication through voice calls, video calls, text messaging, and media.

https://github.com/davidonzo/Threat-Intel/blob/1fe903cbc8bf728a852f47b8bcb0788c2125b285/lists/latestdomains.txt#L25

Also reported here: https://github.com/davidonzo/Threat-Intel/commit/1fe903cbc8bf728a852f47b8bcb0788c2125b285#r146057646

**Comment by HrKnuddel** [comment]
please fix this fast
this is very much a false positive!!!!!!!!!!!!!!!!
@davidonzo

**Comment by HrKnuddel** [comment]
@LXGaming if you want a workaround for now: use Canary or PTB... these use diffrent DNS names. But that doesn't work on mobile

**Comment by davidonzo** [comment]
Fixed => https://github.com/davidonzo/Threat-Intel-Domain-WL/commit/1efa55363670a080077fa3429ce77b7ea2071e49

Lists will be updated in minutes.

**Comment by davidonzo** [comment]
Issue solved.

Thanks all for the support and sorry for the false positive.

**Comment by swilkins1337** [comment]
I would put steps in to ensure entire platforms like Discord don't get blocked just because somebody, somewhere is sharing malware on it.

**Comment by davidonzo** [comment]
I agree with you @swilkins1337 
One way is help me maintaining up to date the whitelist repository => https://github.com/davidonzo/Threat-Intel-Domain-WL

Thanks!
