### ISSUE TITLE
Missing manifest file from MISP feed

### ISSUE THREAD

**Issue by mikkelothar** [davidonzo/Threat-Intel#6]
Hi David
Im trying to get your MISP feed, from within my own MISP installation, but it seems it requires a manifest.json file, which are not present.

Thanks in advance.

![missing_manifest json](https://user-images.githubusercontent.com/16288604/79193279-99a9f500-7e2a-11ea-97c1-99c494cc070c.PNG)

**Comment by davidonzo** [comment]
Sorry, my fault.
Fixed. Please, retry. Services has been restored.

**Comment by mikkelothar** [comment]
Hi David. 
Its up and running again. Thank you :) Closing the issue
