### ISSUE TITLE
codeload.github.com

### ISSUE THREAD

**Issue by notDavid** [davidonzo/Threat-Intel#7]
Hi there,

FYI, I suppose this domain should not be in here? It's breaking HomeBrew downloads...

`codeload.github.com`

**Comment by davidonzo** [comment]
Domain removed and whitelisted.
Thanks a lot!

This is an "half" false positive.
The reason is related to some malicious url using the domain. Very often situation in the social network era.
The malicious URL remain in the urls list, the domain not.
