### ISSUE TITLE
static.wixstatic.com

### ISSUE THREAD

**Issue by bpr97050** [davidonzo/Threat-Intel#8]
I noticed `static.wixstatic.com` was included in the list. However, from the [Wix website](https://support.wix.com/en/article/wix-editor-staticwixstaticcommedia-appears-in-url-of-wix-images):

_Static.wixstatic.com/media is the server where Wix hosts all its images. It allows us to deliver these images to you and your users quickly and efficiently._

Not sure if this is meant to be included or not, but either way I've had to whitelist it in my Pihole in order to access some Wix websites. Maybe someones been abusing Wix?

**Comment by davidonzo** [comment]
Has been detected several RTF files hosted on `static.wixstatic.com` used to spread malwares.

This is why the main domain is included in the domain list.
Of course, in this case it can be considered and half false positive. It's usual for this kind of services.

I'll whitelist the domain, just removed from the [domain list](https://osint.digitalside.it/Threat-Intel/lists/latestdomains.txt).
Related urls will be mainained in [the url list file](https://osint.digitalside.it/Threat-Intel/lists/latesturls.txt). New urls will be reported as well.

Can you close the issue if you think it is solved.

Thanks.
--
DB

**Comment by bpr97050** [comment]
Yep, that works. Thank you!
