### ISSUE TITLE
i.imgur.com

### ISSUE THREAD

**Issue by ACMEd** [davidonzo/Threat-Intel#9]
Imgur is used exclusively to host images, so we can be reasonably confident that it isn’t a threat.

Note: the listed url points to an image which has since been taken down.
`https://i.imgur.com/6WIjvDZ.png`

**Comment by davidonzo** [comment]
The URL is part of a malware attack.

This is why the main domain is included in the domain list.
Of course, in this case it can be considered and half false positive. It's usual for this kind of services.

I'll whitelist the domain, just removed from the [domain list](https://osint.digitalside.it/Threat-Intel/lists/latestdomains.txt).
Related urls will be mainained in [the url list file](https://osint.digitalside.it/Threat-Intel/lists/latesturls.txt). New urls will be reported as well.

Can you close the issue if you think it is solved.

Thanks.
DB
